version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: btcsql-btc-sql-explorer_web_1
      APP_PORT: 5001

  web:
    image: ignaciofdez/btc-sql-explorer:v1.4.1@sha256:bda079a34df1221d6376b5009b6a4dc52f8b9c03b6f937550037515415b69585
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      # Bitcoin Core RPC (injected by Umbrel)
      BITCOIN_RPC_HOST: $APP_BITCOIN_NODE_IP
      BITCOIN_RPC_PORT: $APP_BITCOIN_RPC_PORT
      BITCOIN_RPC_USER: $APP_BITCOIN_RPC_USER
      BITCOIN_RPC_PASS: $APP_BITCOIN_RPC_PASS
      BITCOIN_NETWORK: ${APP_BITCOIN_NETWORK:-mainnet}
      # Persistent data paths
      DB_PATH: /data/bitcoin_blockchain.db
      MEMPOOL_DB_PATH: /data/mempool.db
      SAVED_QUERIES_PATH: /data/saved_queries.db
